<a href="https://colab.research.google.com/github/sjtao98/CSLearning/blob/main/CS7646_Midterm_Python_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This file is created based on https://docs.google.com/document/d/1sVHdIchHNMJro0CbxIBXexCwQ621MPMe-sCG3KTCdEo/pub

In [2]:
import numpy as np
import pandas as pd

df = pd.DataFrame([52, 46, 50, 51], columns = ['AAPL'], index = ['01-01', '01-02', '01-03', '01-04'])

df = df.join(pd.DataFrame([83, 88, 86, 90], columns = ['SPY'], index = ['01-01', '01-02', '01-04', '01-05']))

print(df)

       AAPL   SPY
01-01    52  83.0
01-02    46  88.0
01-03    50   NaN
01-04    51  86.0


In [7]:
d = {"SPY" : [86.80, 86.70, 87.28, 84.67, 85.01],
    "AAPL": [90.36, 94.18, 92.62, 90.62, 92.30],
    "HNZ" : [33.95, 33.82, 33.38, 32.59, 31.99],
    "XOM" : [74.48, 74.47, 73.26, 71.39, 85.13],
    "GLD" : [86.23, 84.48, 85.13, 82.75, 84.46]}

df = pd.DataFrame(d)
print(df)

normed = df/df.loc[0] #df.ix[0]
print(normed)

normed['AAPL'] = np.nan
print(normed)

normed.fillna(value='0')
print(normed)

print(normed[0:2])

     SPY   AAPL    HNZ    XOM    GLD
0  86.80  90.36  33.95  74.48  86.23
1  86.70  94.18  33.82  74.47  84.48
2  87.28  92.62  33.38  73.26  85.13
3  84.67  90.62  32.59  71.39  82.75
4  85.01  92.30  31.99  85.13  84.46
        SPY      AAPL       HNZ       XOM       GLD
0  1.000000  1.000000  1.000000  1.000000  1.000000
1  0.998848  1.042275  0.996171  0.999866  0.979705
2  1.005530  1.025011  0.983211  0.983620  0.987243
3  0.975461  1.002877  0.959941  0.958512  0.959643
4  0.979378  1.021470  0.942268  1.142991  0.979474
        SPY  AAPL       HNZ       XOM       GLD
0  1.000000   NaN  1.000000  1.000000  1.000000
1  0.998848   NaN  0.996171  0.999866  0.979705
2  1.005530   NaN  0.983211  0.983620  0.987243
3  0.975461   NaN  0.959941  0.958512  0.959643
4  0.979378   NaN  0.942268  1.142991  0.979474
        SPY  AAPL       HNZ       XOM       GLD
0  1.000000   NaN  1.000000  1.000000  1.000000
1  0.998848   NaN  0.996171  0.999866  0.979705
2  1.005530   NaN  0.983211  0.983

In [8]:
array = np.ones((2,3,4))
array = array * 2
print(array.sum(axis=None))

48.0


In [9]:
x = True
df1 = pd.DataFrame([[1,0,-5],[2,0,-1],[1,4,0]])
print(df1)

f = lambda x: np.abs(x)>1
df1[f(df1)] = "!!!"
print(df1)

   0  1  2
0  1  0 -5
1  2  0 -1
2  1  4  0
     0    1    2
0    1    0  !!!
1  !!!    0   -1
2    1  !!!    0


In [10]:
a = np.ones((3,3))
print(a)

b = a
b[0,1] = 2

print(b)
print(a)

b = a.copy()   # what should be filled instead of _A_ for below ouputs to be true ?

b[0,1] = 3
print(b)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 3. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
a = np.array([2]*4)

b = np.array([1, 2, 3, 4, 5, 6, 7])
b[1:] * a[-1]

array([ 4,  6,  8, 10, 12, 14])

In [13]:
j = [8, 7, 6, 5, 4, 3, 2, 1]
print(j[-2])
print([x/j[-2] for x in j[1:-1]])

2
[3.5, 3.0, 2.5, 2.0, 1.5, 1.0]


In [14]:
syms=['IBM', 'AAPL', 'HNZ', 'XOM', 'GLD']
prices =  pd.DataFrame(np.random.rand(10, len(syms)),columns=syms)
print(prices.tail(1).values)

[[0.79518586 0.86751754 0.71226448 0.21693529 0.38252749]]


In [15]:
a = np.random.randint(10, 30, size=(2, 4))
print(a)
print(a.size)
print(a.shape[0])
print(a.shape[1])

[[19 24 29 29]
 [27 22 18 26]]
8
2
4


In [17]:
weekSales =  pd.DataFrame(np.random.random([7,3])*100,
            index=['Sun', 'Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat'],
            columns=['Coffee', 'Donuts', 'Bagels'])

print(weekSales)

print(np.sum(np.sum(weekSales)))
print(np.sum(weekSales, axis=1))
print(np.sum(weekSales, axis=0))

          Coffee     Donuts     Bagels
Sun    62.617067  11.009788   1.519111
Mon    26.800183  19.956028  12.004497
Tues    9.613283  41.837002  86.478129
Wed    33.566281  88.818588  90.136684
Thurs   3.973817  42.323564  81.131315
Fri     7.710533   9.343809  47.595444
Sat    71.041699  48.817272  68.811428
865.1055230319482
Sun       75.145966
Mon       58.760708
Tues     137.928413
Wed      212.521554
Thurs    127.428696
Fri       64.649786
Sat      188.670400
dtype: float64
Coffee    215.322864
Donuts    262.106051
Bagels    387.676608
dtype: float64


In [20]:
x = np.array([[1,2,3,4],
             [4,5,6,7],
             [8,9,0,1]])

print(x[:,[0,2]])

[[1 3]
 [4 6]
 [8 0]]


In [25]:
dates = pd.date_range('2015-01-01', '2015-01-04', name='Date')
df = pd.DataFrame(index=dates)
df['count'] = [i for i in range(len(df))]

print(df)

df = df.reset_index(['Date'])
print(df)

df.set_index('count', inplace=True)
print(df)

            count
Date             
2015-01-01      0
2015-01-02      1
2015-01-03      2
2015-01-04      3
        Date  count
0 2015-01-01      0
1 2015-01-02      1
2 2015-01-03      2
3 2015-01-04      3
            Date
count           
0     2015-01-01
1     2015-01-02
2     2015-01-03
3     2015-01-04


In [27]:
df = np.array([2, 3, 4, 5])
#print(pd.rolling_mean(df, window=2))
print(pd.Series(df).rolling(window=2).mean())

0    NaN
1    2.5
2    3.5
3    4.5
dtype: float64


In [29]:
a = np.arange(5, 0, -1)
print(a)
print(a[a < 3])

[5 4 3 2 1]
[2 1]


In [31]:
df1 = pd.DataFrame([[10, 'w'],
                   [20, 'x'],
                   [30, 'y'],
                   [40, 'z']],
                 columns=['numbers', 'letters'],
                 index=['a', 'b', 'c', 'd'])


df2 = pd.DataFrame([[1.0, '#'],
                   [2.0, '@'],
                   [3.0, '%'],
                   [4.0, '$']],
                 columns=['floats', 'symbols'],
                 index=['a', 'b', 'c', 'e'])

print(df1.join(df2, how='right'))
print(df1.join(df2, how='inner'))
print(df1.join(df2, how='outer'))
print(df1.join(df2, how='left'))

   numbers letters  floats symbols
a     10.0       w     1.0       #
b     20.0       x     2.0       @
c     30.0       y     3.0       %
e      NaN     NaN     4.0       $
   numbers letters  floats symbols
a       10       w     1.0       #
b       20       x     2.0       @
c       30       y     3.0       %
   numbers letters  floats symbols
a     10.0       w     1.0       #
b     20.0       x     2.0       @
c     30.0       y     3.0       %
d     40.0       z     NaN     NaN
e      NaN     NaN     4.0       $
   numbers letters  floats symbols
a       10       w     1.0       #
b       20       x     2.0       @
c       30       y     3.0       %
d       40       z     NaN     NaN


In [34]:
j=np.random.random([4,4])
print(j)
print(j[1:3, 2:])

[[0.94026013 0.66188796 0.90505363 0.10591468]
 [0.85776298 0.68528956 0.77996127 0.52642608]
 [0.36404891 0.7433417  0.23152597 0.33431678]
 [0.89030492 0.27138348 0.03080082 0.30348961]]
[[0.77996127 0.52642608]
 [0.23152597 0.33431678]]


In [35]:
a = np.random.randint(0,10,size=(3,3))
print ("Matrix a is ",a)
value = np.mean(a.min(axis = 0))
print ("Variable value is", value)

Matrix a is  [[8 2 4]
 [7 7 1]
 [7 3 3]]
Variable value is 3.3333333333333335


In [38]:
ary = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])
print(ary[:, :, 0])
print(ary[:, 0, :])
print(ary[0, :, :])

[[1 3]
 [5 7]]
[[1 2]
 [5 6]]
[[1 2]
 [3 4]]


In [39]:
a = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])

print(a[:,1:5:2])

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]


In [40]:
a=np.ones((3,3))*2
b=a.dot(a)
print(a)
print(b)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[12. 12. 12.]
 [12. 12. 12.]
 [12. 12. 12.]]


In [41]:
df1 = pd.DataFrame( {'var1': [1,2,3,4,5], 'var2': [11,12,13,14,15]}, index = ['cat','dog', 'bird', 'fish', 'turtle'] )
df2 = pd.DataFrame( {'var3': [101,102,103,104,105]}, index = ['dog', 'bird', 'cat', 'turtle', 'fish'] )
df3 = df1.join(df2)

print(df1)
print(df2)
print(df3)
print(df3.loc['bird','var2']) #ix


        var1  var2
cat        1    11
dog        2    12
bird       3    13
fish       4    14
turtle     5    15
        var3
dog      101
bird     102
cat      103
turtle   104
fish     105
        var1  var2  var3
cat        1    11   103
dog        2    12   101
bird       3    13   102
fish       4    14   105
turtle     5    15   104
13


In [45]:
df = pd.DataFrame(np.random.randn(5, 3), index=['2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-08'], columns=['a', 'b', 'c'])
df = df.reindex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05','2013-01-07', '2013-01-08', '2013-01-09'])
print(df)
df.fillna(method='ffill', inplace=True)
print(df)
df.fillna(method='bfill', inplace=True)
print(df)

                   a         b         c
2013-01-01       NaN       NaN       NaN
2013-01-02 -0.453618  0.032285 -0.066579
2013-01-03 -0.185006 -1.065728 -1.527742
2013-01-04 -0.508177 -0.927670  0.536210
2013-01-05  0.373791 -0.887297 -0.233123
2013-01-07       NaN       NaN       NaN
2013-01-08  0.276597  2.129731  0.957932
2013-01-09       NaN       NaN       NaN
                   a         b         c
2013-01-01       NaN       NaN       NaN
2013-01-02 -0.453618  0.032285 -0.066579
2013-01-03 -0.185006 -1.065728 -1.527742
2013-01-04 -0.508177 -0.927670  0.536210
2013-01-05  0.373791 -0.887297 -0.233123
2013-01-07  0.373791 -0.887297 -0.233123
2013-01-08  0.276597  2.129731  0.957932
2013-01-09  0.276597  2.129731  0.957932
                   a         b         c
2013-01-01 -0.453618  0.032285 -0.066579
2013-01-02 -0.453618  0.032285 -0.066579
2013-01-03 -0.185006 -1.065728 -1.527742
2013-01-04 -0.508177 -0.927670  0.536210
2013-01-05  0.373791 -0.887297 -0.233123
2013-01-07  0.37

In [46]:
k= np.array([[2, 4, 8, 16], [16.0, 8.0, 4.0, 2.0]])

print(k[1,2:-1]/k[-2,-2])

[0.5]


In [48]:
j = np.array([(1,2,3),(4,5,6),(7,8,9)])
k = j[:,-1:]
print(k)
print(k.shape)

[[3]
 [6]
 [9]]
(3, 1)


In [49]:
syms=['GOOG','AAPL','GLD','XOM']
num_syms = len(syms)
allocs = [1.0 / num_syms] * num_syms
print(allocs)

[0.25, 0.25, 0.25, 0.25]


In [51]:
df1 = pd.DataFrame({'Type': ["Stock", None]})
df2 = df1
print(df1)
print(df2)

df1.fillna("Mutual Fund", inplace=True)
df2.fillna("ETF")

print(df1)
print(df2)

    Type
0  Stock
1   None
    Type
0  Stock
1   None
          Type
0        Stock
1  Mutual Fund
          Type
0        Stock
1  Mutual Fund


In [54]:
array0 = np.array([3,2,5,2,1])
df = pd.DataFrame(array0, columns=['numbers'], index=['a','b','c','d','e'])
print(df)
df = df.loc[df.index[2:5]].sum() #ix
print(df)
dr = df**2
print(df)
print(dr)

   numbers
a        3
b        2
c        5
d        2
e        1
numbers    8
dtype: int64
numbers    8
dtype: int64
numbers    64
dtype: int64


Given a CSV file that contains the following data:

Name,Value,Company,Founded

George Soros,4000000000,Soros Fund Management,1969

Tucker Balch,1000000000000,Lucena Research,

df = pd.read_csv('top_hedgefund_managers.csv', index_col="Company").sort(columns='Value', ascending=False).fillna('TBD')

print(df)

output:

                   Name          Value Founded   Company

Lucena Research        Tucker Balch  1000000000000     TBD

Soros Fund Management  George Soros     4000000000    1969

In [56]:
m = np.array([[1, 3, 5], [2, 4, 6]])
n = np.array([[1, 2, 3], [1, 2, 3]])
print(np.sum(m, axis=0))
print(np.mean(n,axis=0))
print(np.sum(m, axis=0)+np.mean(n,axis=0))

[ 3  7 11]
[1. 2. 3.]
[ 4.  9. 14.]


In [57]:
a = np.array([1,2,3,4,5])
print (a * a[::-1])

[5 8 9 8 5]


In [58]:
data = {'A': [100, 60, 30, 130], 'B': [5, 15, 15, 5],'C': [100, 300, 100, 200],'D': [20, 20, 30, 30]}
df = pd.DataFrame(data)
print(df)

df = df.shift(2)
print(df)
print(df.mean())

     A   B    C   D
0  100   5  100  20
1   60  15  300  20
2   30  15  100  30
3  130   5  200  30
       A     B      C     D
0    NaN   NaN    NaN   NaN
1    NaN   NaN    NaN   NaN
2  100.0   5.0  100.0  20.0
3   60.0  15.0  300.0  20.0
A     80.0
B     10.0
C    200.0
D     20.0
dtype: float64


In [59]:
a = [[]]*4
print(a)

a[0].append(15)
print(a)

[[], [], [], []]
[[15], [15], [15], [15]]


In [65]:
df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
print(df)

print(df.drop("B", axis=1))
print(df)

   A  B
0  1  3
1  2  4
   A
0  1
1  2
   A  B
0  1  3
1  2  4


In [67]:
i= [1,2,3,4,5,6]
d = [2,2.5,2.99,3.5,3.8,10]
df = pd.DataFrame(index=i, data=d)
print(df)
print(df/df.shift(1) - 1)

       0
1   2.00
2   2.50
3   2.99
4   3.50
5   3.80
6  10.00
          0
1       NaN
2  0.250000
3  0.196000
4  0.170569
5  0.085714
6  1.631579


In [68]:
x = np.array([[0,1,2],[3,4,5],[4,3,2]])
x = x**2
print(x)
print(x[-1] * x[1])

[[ 0  1  4]
 [ 9 16 25]
 [16  9  4]]
[144 144 100]


In [71]:
s = pd.DataFrame([0, 1, 2, np.nan])
print("size", s.size)
print("count:", s.count())

size 4
count: 0    3
dtype: int64


In [73]:
df = pd.DataFrame(np.array([(1,2),(3,4),(5,6)]),index=['a','c','e'],columns=['data1','data2'])
df = df.reindex(['a','b','c','d','e'])
print(df)
df = df.fillna(method='ffill')
print(df)
df = df.sum(axis=1)
print(df)

   data1  data2
a    1.0    2.0
b    NaN    NaN
c    3.0    4.0
d    NaN    NaN
e    5.0    6.0
   data1  data2
a    1.0    2.0
b    1.0    2.0
c    3.0    4.0
d    3.0    4.0
e    5.0    6.0
a     3.0
b     3.0
c     7.0
d     7.0
e    11.0
dtype: float64


In [75]:
arr = np.ones([1,5])
df = pd.DataFrame(arr)
print(df)
df.loc[:,2:3] = 0  #ix
print(df)
print(df.values)

     0    1    2    3    4
0  1.0  1.0  1.0  1.0  1.0
     0    1    2    3    4
0  1.0  1.0  0.0  0.0  1.0
[[1. 1. 0. 0. 1.]]


In [77]:
m = np.arange(20).reshape(4,5)
print(m)
print(m.cumsum(axis=1))
print(m.cumsum(axis=0))
print(m.sum(axis=1))
print(m.sum(axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  3  6 10]
 [ 5 11 18 26 35]
 [10 21 33 46 60]
 [15 31 48 66 85]]
[[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]
 [30 34 38 42 46]]
[10 35 60 85]
[30 34 38 42 46]


In [82]:
df = np.array([25,4,78,54,6,21,45,2])
print(pd.Series(df).rolling(window=2, min_periods=2).max())
print(pd.Series(df).rolling(window=2).max())

0     NaN
1    25.0
2    78.0
3    78.0
4    54.0
5    21.0
6    45.0
7    45.0
dtype: float64
0     NaN
1    25.0
2    78.0
3    78.0
4    54.0
5    21.0
6    45.0
7    45.0
dtype: float64


In [83]:
A = np.zeros((4,4), dtype=int)
A[1::2, ::2] = 1
print(A)

A[::2, 1::2] = 1
print(A)

[[0 0 0 0]
 [1 0 1 0]
 [0 0 0 0]
 [1 0 1 0]]
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [84]:
x = np.random.randint(5, size=(4, 5))
print(x)

x[1][::2] = 777
print(x)

[[4 0 2 2 3]
 [2 4 4 2 2]
 [3 0 2 3 4]
 [4 4 1 3 3]]
[[  4   0   2   2   3]
 [777   4 777   2 777]
 [  3   0   2   3   4]
 [  4   4   1   3   3]]


In [86]:
red = np.array([[3,4],[2,4]])
x = ([2,5],[2,3])
x = np.asarray(x)
blue = red * x[-2,:]
print(x[-2,:])
print(blue)

[2 5]
[[ 6 20]
 [ 4 20]]


In [87]:
arr = np.array([[1,2,5],[2,4,2],[3,3,2]])
x = arr[:,1].sum(),arr[0:].sum().sum(axis=0)
print(x)

(9, 24)


In [88]:
x = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9],[10, 11, 12, 13, 14]])
print(x)
print(x[0:2,3:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[3]
 [8]]


In [89]:
j = np.array([(1,2,3),(4,5,6),(7,8,9)])
k = j[:,-1:]
print(k.shape)

(3, 1)


In [91]:
a= np.array([[4,1, 6, 9], [4, 9, 2, 5], [7, 0, 9, 7], [6, 1, 9, 5], [6, 6, 3, 9]])
print(a[1:3,1:2].sum())

9


In [96]:
data = { 'key': [ 'B','D','C','A' ], 'value': [ 1,2,3,4 ]}
sub = pd.DataFrame.from_dict( data ).sort_values([ 'key' ]).loc[ 0:1 ] #ix
print(sub.value.mean())

2.0


In [99]:
r = np.random.randint(20, size=(4, 6))
print(r)

r[np.where(r[:,1]>10),1]

[[ 6 12  9  1  4 11]
 [19  1  1  8 14 12]
 [17  6 19  7  8 12]
 [ 8 17 12  8  6 16]]


array([[12, 17]])

In [102]:
x = np.array([8,1,3,4,5,2,1,9,6,4,7])
print(x[2:7])
print(x[2:7][::-1])
print(x[2:7][::-1][:-1])
print(np.mean(x[2:7][::-1][:-1]))

[3 4 5 2 1]
[1 2 5 4 3]
[1 2 5 4]
3.0


In [103]:
a = np.array([2, 7, 11, 9, 3])
a[a < 5] = 5
a[2] = 10
print(a)

[ 5  7 10  9  5]


In [107]:
a = pd.Series([1, 2, 4, 7, 11, 16])
b = a-a.shift(1)
print(a)
print(b)
print(b.values[-1]*1.0)

0     1
1     2
2     4
3     7
4    11
5    16
dtype: int64
0    NaN
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
dtype: float64
5.0


In [109]:
data = [1.0, 1.05, 1.2, 0.99, 1.5]

# create dates starting Jan 1st and ending Jan 5th
ind = pd.date_range(start='2016-01-01', end='2016-01-05')
name = ['daily_returns']
df = pd.DataFrame(data=data, index=ind, columns=name)
a = df['daily_returns'] - df['daily_returns'].mean()
b = (a**2).sum()
c = df.shape[0]-1

# return The sample standard deviation of daily_returns
print((b/c)**0.5)


0.21393924371185385


In [110]:
a = np.random.random([5])
print(a)
print(a[-5:-3])

[0.63486956 0.26155276 0.7862306  0.01538735 0.37111479]
[0.63486956 0.26155276]
